name: test

on:
  pull_request:
    branches: master
  push:
    branches: master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Prepare
        id: prepare
        run: |
          echo ::set-output name=build_tag::test
          echo ::set-output name=container_name::unifi
          echo ::set-output name=running_timeout::60
          echo ::set-output name=running_log_check::Listening on
      -
        # https://github.com/actions/checkout
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Checkout jacobalberty/unifi-docker tag 5.12.66
        uses: actions/checkout@v2
          with:
            repository: jacobalberty/unifi-docker
            ref: '5.12.66'
            path: unifi-docker
      -
        # https://github.com/crazy-max/ghaction-docker-buildx
        # sha = https://github.com/crazy-max/ghaction-docker-buildx/releases/tag/v1.0.4
        name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@e193644d92840c3a0d2a80093feff3a0d8d64e7e
        with:
          version: latest
      -
        name: Docker Buildx
        run: |
          cd unifi-docker
          docker buildx build --load --tag ${{ steps.prepare.outputs.build_tag }} --file Dockerfile .
      -
        name: Start container
        run: |
          docker rm -f ${{ steps.prepare.outputs.container_name }} > /dev/null 2>&1 || true
          mkdir -p unifi/data
          mkdir -p unifi/log
          docker run -d --rm --init \
          --name ${{ steps.prepare.outputs.container_name }} \
          -p 8080:8080 -p 8443:8443 -p 3478:3478/udp -p 10001:10001/udp \
          -e TZ='America/New_York' \
          -v "${PWD}/unifi:/unifi" \
          ${{ steps.prepare.outputs.build_tag }}
      -
        name: Test run
        run: |
          # TIMEOUT=$((SECONDS + ${{ steps.prepare.outputs.running_timeout }}))
          # while read LOGLINE; do
          #   echo ${LOGLINE}
          #   if [[ ${LOGLINE} == *"${{ steps.prepare.outputs.running_log_check }}"* ]]; then
          #     echo "Container up!"
          #     break
          #   fi
          #   if [[ $SECONDS -gt ${TIMEOUT} ]]; then
          #     >&2 echo "ERROR: Failed to run ${{ steps.prepare.outputs.container_name }} container"
          #     docker rm -f ${{ steps.prepare.outputs.container_name }} > /dev/null 2>&1 || true
          #     exit 1
          #   fi
          # done < <(docker logs -f ${{ steps.prepare.outputs.container_name }} 2>&1)
          CONTAINER_STATUS=$(docker container inspect --format "{{.State.Status}}" ${{ steps.prepare.outputs.container_name }})
          if [[ ${CONTAINER_STATUS} != "running" ]]; then
            >&2 echo "ERROR: Container ${{ steps.prepare.outputs.container_name }} returned status '$CONTAINER_STATUS'"
            docker rm -f ${{ steps.prepare.outputs.container_name }} > /dev/null 2>&1 || true
            exit 1
          fi
          docker rm -f ${{ steps.prepare.outputs.container_name }} > /dev/null 2>&1 || true
          echo